[package]
name = "mcp"
version = "0.1.0"
edition = "2024"

[lib]
name = "mcp"
path = "src/lib.rs"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full", "process"] }
